version: '3.3'
services:

  # Prometheus uses the image resulting form the build
  # of `./prometheus` which simply packs some configuration
  # into the form of an image.
  #
  # It could instead, use volume-mounts.
  prometheus:
    build: './prometheus'
    container_name: 'prometheus'
    ports:
      - '9090:9090'

  # The grafana container uses the image resulting from the build
  # of `./grafana` which simply packs some configuration into the
  # form of an image.
  #
  # This could instead be a volume-mounted container.
  grafana:
    build: './grafana'
    container_name: 'grafana'
    ports:
      - '3000:3000'

  # You'd typically not run `node_exporter` in a container like
  # this.
  # If so, make sure you're using `network_mode=host` to give the
  # host network namespace to the containers as well as `pid=host`. 
  # 
  # Eventually it would also make sense to extend it with other 
  # privileges and mounts. 
  #
  # I've never ran it in a container so I can't endorse doing so.
  node_exporter:
    image: 'quay.io/prometheus/node-exporter'
    container_name: 'node_exporter'

